artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    project_source_file: data/winequality-red.csv
    project_raw_file: artifacts/data_ingestion/winequality.csv

data_validation:
    root_dir: artifacts/data_validation
    data_file: artifacts/data_ingestion/winequality.csv
    STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
    root_dir: artifacts/data_transformation
    data_file: artifacts/data_ingestion/winequality.csv
